In [1]:
# https://raw.githubusercontent.com/guilhermeonrails/i-eng-dados-26/refs/heads/main/dados.csv
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/i-eng-dados-26/refs/heads/main/dados.csv") # read the CSV file into a Pandas DataFrame

In [2]:
df.head(5) # display the first 5 rows

,id_usuario,home,pesquisou_produto,visualizou_detalhes,acessou_faq,acessou_ofertas,adicionou_carrinho,finalizou_compra,codigo_compra,valor_total
0,USR1000001,1,1,1,0,1,1,0,NaN,NaN
1,USR1000002,1,1,1,0,1,0,0,NaN,NaN
2,USR1000003,1,1,0,1,1,0,0,NaN,NaN
3,USR1000004,1,1,1,0,0,0,0,NaN,NaN
4,USR1000005,1,0,0,1,0,0,0,NaN,NaN

In [3]:
df.info() # display the data types of each column

<class 'pandas.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id_usuario           495000 non-null  str
 1   home                 500000 non-null  int64
 2   pesquisou_produto    500000 non-null  int64
 3   visualizou_detalhes  500000 non-null  int64
 4   acessou_faq          500000 non-null  int64
 5   acessou_ofertas      500000 non-null  int64
 6   adicionou_carrinho   500000 non-null  int64
 7   finalizou_compra     500000 non-null  int64
 8   codigo_compra        39726 non-null   str
 9   valor_total          39726 non-null   float64
dtypes: float64(1), int64(7), str(2)
memory usage: 38.1 MB

In [4]:
df.describe() # display the summary statistics of each column

,home,pesquisou_produto,visualizou_detalhes,acessou_faq,acessou_ofertas,adicionou_carrinho,finalizou_compra,valor_total
count,500000.00000,500000.000000,500000.00000,500000.000000,500000.000000,500000.000000,500000.000000,39726.000000
mean,0.93949,0.533002,0.53997,0.468458,0.200884,0.449874,0.079452,2595.594113
std,0.23843,0.498910,0.49840,0.499005,0.400662,0.497482,0.270443,1385.993411
min,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,180.080000
25%,1.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1388.942500
50%,1.00000,1.000000,1.00000,0.000000,0.000000,0.000000,0.000000,2603.135000
75%,1.00000,1.000000,1.00000,1.000000,0.000000,1.000000,0.000000,3785.607500
max,1.00000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,4998.960000

In [5]:
df.isnull().sum() # display the number of missing values in each column

id_usuario               5000
home                        0
pesquisou_produto           0
visualizou_detalhes         0
acessou_faq                 0
acessou_ofertas             0
adicionou_carrinho          0
finalizou_compra            0
codigo_compra          460274
valor_total            460274
dtype: int64

In [6]:
df.duplicated().sum() # display the number of duplicate

np.int64(4546)

In [7]:
df["id_usuario"] = df["id_usuario"].fillna("USER_DESCONHECIDO") # fill the missing values in the column 'id_usuario' with the string 'USER_DESCONHECIDO'

In [8]:
df[df["id_usuario"] == "USER_DESCONHECIDO"] # display the rows where the column 'id_usuario' is equal to 'USER_DESCONHECIDO'

,id_usuario,home,pesquisou_produto,visualizou_detalhes,acessou_faq,acessou_ofertas,adicionou_carrinho,finalizou_compra,codigo_compra,valor_total
212,USER_DESCONHECIDO,1,0,0,1,1,0,0,NaN,NaN
299,USER_DESCONHECIDO,1,1,0,0,0,0,0,NaN,NaN
354,USER_DESCONHECIDO,1,1,0,1,0,1,0,NaN,NaN
569,USER_DESCONHECIDO,1,0,0,0,0,0,0,NaN,NaN
603,USER_DESCONHECIDO,1,0,1,0,0,1,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
499648,USER_DESCONHECIDO,1,1,1,1,1,1,0,NaN,NaN
499858,USER_DESCONHECIDO,1,1,1,0,0,1,1,CMP160834,4541.79
499872,USER_DESCONHECIDO,1,0,1,0,0,0,0,NaN,NaN
499908,USER_DESCONHECIDO,1,1,1,0,0,1,1,CMP200979,3048.02
499957,USER_DESCONHECIDO,1,0,1,0,0,1,0,NaN,NaN

In [9]:
df.isnull().sum() # display the number of missing values in each column

id_usuario                  0
home                        0
pesquisou_produto           0
visualizou_detalhes         0
acessou_faq                 0
acessou_ofertas             0
adicionou_carrinho          0
finalizou_compra            0
codigo_compra          460274
valor_total            460274
dtype: int64

In [10]:
import os

os.environ["JAVA_HOME"] = r"C:\Program Files\Java\jdk-26.0.2.1\bin"
os.environ["PATH"] = os.environ["JAVA_HOME"] + r"\bin;" + os.environ["PATH"]

In [13]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[2]").appName("Exemplo PySpark").getOrCreate()

dados_spark = spark.createDataFrame(df)
dados_spark.createOrReplaceTempView("dados")

KeyboardInterrupt:

In [ ]:
%%sql
SELECT * FROM dados LIMIT 5